const express = require('express');
const router = express.Router();
const mongodbPromise = require('../utils/mongodb');
const { bookingSchema, bookingCreationSchema } = require('../schemas/booking');

const SERVICE_LABELS = {
    services: 'Shower Services',
    laundry:  'Laundry',
    market:   'Market',
};

function serviceLabel(serviceID) {
    return SERVICE_LABELS[serviceID] || serviceID;
}

function notifTimestamp() {
    return new Date().toLocaleString('en-US', {
        weekday: 'long',
        month:   'short',
        day:     '2-digit',
        hour:    'numeric',
        minute:  '2-digit',
        hour12:  true,
    });
}

async function sendBookingNotification(client, { receiverID, bookingID, title, message, type = 'UPDATE' }) {
    try {
        await client.db('notifications').collection('notifications').insertOne({
            senderID:    'system',
            receiverID,
            bookingID,
            type,
            isRead:      false,
            wasNotified: false,
            title,
            message,
            timestamp:   new Date().toISOString(),
        });
    } catch (err) {
        console.error('Failed to create booking notification:', err);
    }
}

/**
 * Booking Routes
 *
 * ENDPOINTS:
 * - POST /create          - Create a new booking
 * - PUT /edit             - Update an existing booking
 * - DELETE /delete        - Delete a booking
 * - POST /userbookinghistory - Get all bookings for a user
 * - POST /reset-counter   - Reset booking ID counter (testing only)
 *
 * WHAT CLIENT PASSES TO /create:
 * - userID: string        - ID of the authenticated user (e.g., "YA_1")
 * - serviceID: string     - Type of service (e.g., "services", "laundry")
 * - duration: array       - Array with day and time info:
 *     - day: string       - Day of week (e.g., "monday", "tuesday")
 *     - startTime: string - Start time in HH:mm format (e.g., "09:00")
 *     - endTime: string   - End time in HH:mm format (e.g., "10:00")
 * - clientName: string    - Display name for the client (e.g., "John Doe")
 * - timestamp: string     - Date the booking is for
 *
 * AUTO-GENERATED BY SERVER:
 * - bookingID: number            - Auto-incrementing unique ID
 * - status: string               - Always starts as 'pending'
 * - activity: [{string: string}] - Activity log of the booking
 */

// POST /create - Create a new booking
router.post('/create', async (req, res) => {
    try {

        const { error: inputError } = bookingCreationSchema.validate(req.body);

        if (inputError) {
            return res.status(400).send(inputError.details[0].message);
        }
        
        // Get MongoDB client and connect to services database
        const client = await mongodbPromise;
        const database = client.db('services');
        const bookingsCollection = database.collection('bookings');

        // Prevent duplicate bookings: one per user per service per day
        const duplicate = await bookingsCollection.findOne({
            userID: req.body.userID,
            serviceID: req.body.serviceID,
            timestamp: req.body.timestamp,
            status: 'confirmed',
        });

        if (duplicate) {
            return res.status(409).json({
                success: false,
                message: 'You already have a booking for this service on this date.',
            });
        }

        const generateBookingID = () => {
            return Array.from({ length: 5 }, () => 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
            .charAt(Math.floor(Math.random() * 36))).join('');
        };

        let bookingID;
        let bookingIDExists = false;

        // Checking if the generated ID exists in Mongo
        while (!bookingIDExists) {
            bookingID = generateBookingID();
            const result = await bookingsCollection.findOne({ bookingID });
            bookingIDExists = !result ? true : false; //kill loop if bookingID doesn't exist

        }

        const date = new Date().toLocaleString('en-US', {
                                    weekday: 'long',
                                    month: 'short',
                                    day: 'numeric',
                                    hour: 'numeric',
                                    minute: '2-digit',
                                    hour12: true
                                });

        // Build the booking data with auto-generated fields
        const bookingData = {
            userID: req.body.userID,
            serviceID: req.body.serviceID,
            bookingID,
            status: 'confirmed',
            timestamp: req.body.timestamp,
            duration: req.body.duration,
            clientName: req.body.clientName || '',
            notes: req.body.notes || '',
            activity: [
                ['created', `Created on ${ date }`],
                ...(req.body.notes ? [['note', `Left on ${ date }.`]] : [])
            ]
        };

        // Validate the complete booking data against Joi schema
        const { error } = bookingSchema.validate(bookingData);

        if (error) {
            return res.status(400).json({
                success: false,
                message: 'Validation error',
                error: error.details[0].message
            });
        }

        // Insert the booking into MongoDB
        const result = await bookingsCollection.insertOne(bookingData);

        await sendBookingNotification(client, {
            receiverID: bookingData.userID,
            bookingID:  bookingData.bookingID,
            title:      'Booking Confirmed',
            message:    `Your ${serviceLabel(bookingData.serviceID)} booking has been confirmed.`,
        });

        if (bookingData.notes) {
            await sendBookingNotification(client, {
                receiverID: 'staff-inbox',
                bookingID:  bookingData.bookingID,
                title:      'Note on New Booking',
                message:    `${bookingData.clientName || bookingData.userID} left a note on their new ${serviceLabel(bookingData.serviceID)} booking.`,
                type:       'ALERT',
            });
        }

        return res.status(201).json({
            success: true,
            message: 'Booking created successfully',
            data: {
                _id: result.insertedId,
                bookingID: bookingData.bookingID,
                userID: bookingData.userID,
                serviceID: bookingData.serviceID,
                status: bookingData.status,
                timestamp: bookingData.timestamp,
                duration: bookingData.duration,
                clientName: bookingData.clientName
            }
        });

    } catch (error) {
        console.log(error);

        // Handle duplicate bookingID error
        if (error.code === 11000) {
            return res.status(409).json({
                success: false,
                message: 'Booking already exists',
                error: 'Duplicate bookingID'
            });
        }

        res.status(500).json({
            success: false,
            message: 'Error creating booking',
            error: error.message
        });
    }
});

// PUT /edit - Edit an existing booking's status and/or duration
// Client passes: bookingID and optionally status and/or duration
router.put('/edit', async (req, res) => {
    try {
        // Get MongoDB client and connect to services database
        const client = await mongodbPromise;
        const database = client.db('services');
        const bookingsCollection = database.collection('bookings');

        const {
            bookingID, status, duration, clientName, serviceID, timestamp: bookingDate, notes, messageResponse,
            timeRequest, timeResponse,
        } = req.body;

        // Validate required field
        if (!bookingID) {
            return res.status(400).json({
                success: false,
                message: 'Validation error',
                error: 'Valid bookingID is required'
            });
        }

        // Check that at least one field to update is provided
        if (!status && !duration && !clientName && !serviceID && !bookingDate && notes === undefined && !messageResponse && !timeRequest && !timeResponse) {
            return res.status(400).json({
                success: false,
                message: 'Validation error',
                error: 'At least one field (status, duration, clientName, serviceID,'
                     + ' timestamp, notes, or messageResponse) must be provided for update'
            });
        }

        const activityTimestamp = new Date().toLocaleString('en-US', {
            weekday: 'long',
            month: 'short',
            day: 'numeric',
            hour: 'numeric',
            minute: '2-digit',
            hour12: true
        });

        // Build the update object dynamically
        const updateFields = {
            activity: []
        };

        const hasFieldChanges = status !== undefined || duration !== undefined
            || clientName !== undefined || serviceID !== undefined
            || bookingDate !== undefined || notes !== undefined;

        // Validate and add status if provided
        if (status !== undefined) {
            const validStatuses = ['confirmed', 'canceled'];
            if (!validStatuses.includes(status)) {
                return res.status(400).json({
                    success: false,
                    message: 'Validation error',
                    error: `status must be one of: ${validStatuses.join(', ')}`
                });
            }
            const activityType = status === 'canceled' ? 'canceled' : 'modified';
            const capitalizedStatus = status.charAt(0).toUpperCase() + status.slice(1);

            updateFields.activity.push([activityType, `${capitalizedStatus} on ${timestamp}`]);
            updateFields.status = status;
        } else if (hasFieldChanges) {
            updateFields.activity.push(['modified', `Modified on ${timestamp}.`]);
        }

        // Validate and add duration if provided
        if (duration !== undefined) {
            const Joi = require('joi');
            const durationSchema = Joi.object({
                    day: Joi.string().valid('sunday', 'monday', 'tuesday', 'wednesday',
                                            'thursday', 'friday', 'saturday').required(),
                    startTime: Joi.string().pattern(/^\d{2}:\d{2}$/).required(),
                    endTime: Joi.string().pattern(/^\d{2}:\d{2}$/).required()
                }).required();

            const { error } = durationSchema.validate(duration);
            if (error) {
                return res.status(400).json({
                    success: false,
                    message: 'Validation error',
                    error: error.details[0].message
                });
            }
            updateFields.duration = duration;
        }

        // Add timestamp (booking date) if provided
        if (newTimestamp !== undefined) {
            updateFields.timestamp = newTimestamp;
        }

        // Add clientName if provided
        if (clientName !== undefined) {
            updateFields.clientName = clientName;
        }

        // Add serviceID if provided
        if (serviceID !== undefined) {
            updateFields.serviceID = serviceID;
        }

        // Add notes if provided
        if (notes !== undefined) {
            updateFields.notes = notes;
            if (notes) updateFields.activity.push(['note', `Left on ${timestamp}.`]);
        }

        // Record that staff sent a message in response to a note
        if (messageResponse) {
            updateFields.activity.push(['messaged', notifTimestamp()]);
        }

        // YA requests extra time — check for conflicts before recording
        let hasConflict = false;
        if (timeRequest) {
            const currentBooking = await bookingsCollection.findOne({ bookingID });
            if (!currentBooking) {
                return res.status(404).json({ success: false, message: 'Booking not found' });
            }
            const [h, m] = currentBooking.duration.endTime.split(':').map(Number);
            const total = h * 60 + m + 30;
            const proposedEnd = `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`;
            const conflictBooking = await bookingsCollection.findOne({
                bookingID: { $ne: bookingID },
                serviceID: currentBooking.serviceID,
                status: 'confirmed',
                'duration.day': currentBooking.duration.day,
                'duration.startTime': { $gte: currentBooking.duration.endTime, $lt: proposedEnd },
            });
            if (conflictBooking) {
                hasConflict = true;
                return res.status(200).json({ success: true, conflict: true });
            }
            updateFields.activity.push(['time', '+30 minutes', notifTimestamp()]);
        }

        // Staff approves or rejects a time extension request
        if (timeResponse === 'approved') {
            const currentBooking = await bookingsCollection.findOne({ bookingID });
            if (!currentBooking) {
                return res.status(404).json({ success: false, message: 'Booking not found' });
            }
            const [h, m] = currentBooking.duration.endTime.split(':').map(Number);
            const total = h * 60 + m + 30;
            updateFields['duration.endTime'] = `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`;
            updateFields.activity.push(['approved', notifTimestamp()]);
        } else if (timeResponse === 'rejected') {
            updateFields.activity.push(['rejected', notifTimestamp()]);
        }

        // Validate and add timestamp (booking date) if provided
        if (bookingDate !== undefined) {
            if (!/^\d{4}-\d{2}-\d{2}$/.test(bookingDate)) {
                return res.status(400).json({
                    success: false,
                    message: 'Validation error',
                    error: 'timestamp must be in YYYY-MM-DD format'
                });
            }
            updateFields.timestamp = bookingDate;
        }

        // Find and update the booking
        const { activity, ...setFields } = updateFields;

        const updatedBooking = await bookingsCollection.findOneAndUpdate(
            { bookingID: bookingID },
            { 
                $set: setFields,
                $push: { activity: { $each: activity } }
            },
            { returnDocument: 'after' } // Return the updated document
        );

        // Check if booking was found
        if (!updatedBooking) {
            return res.status(404).json({
                success: false,
                message: 'Booking not found',
                error: `No booking found with bookingID: ${bookingID}`
            });
        }

        const svcLabel        = serviceLabel(updatedBooking.serviceID);
        const hasNewNote      = notes !== undefined && !!notes;
        const hasOtherChanges = status !== undefined || duration !== undefined
                             || bookingDate !== undefined || clientName !== undefined
                             || serviceID !== undefined;

        if (hasOtherChanges) {
            await sendBookingNotification(client, {
                receiverID: updatedBooking.userID,
                bookingID:  updatedBooking.bookingID,
                title:      status === 'canceled' ? 'Booking Canceled' : 'Booking Updated',
                message:    status === 'canceled'
                    ? `Your ${svcLabel} booking has been canceled.`
                    : `Your ${svcLabel} booking has been updated.`,
            });
        }

        if (hasNewNote) {
            await sendBookingNotification(client, {
                receiverID: 'staff-inbox',
                bookingID:  updatedBooking.bookingID,
                title:      'Note Added to Booking',
                message:    `${updatedBooking.clientName || updatedBooking.userID} left a note on their ${svcLabel} booking.`,
                type:       'ALERT',
            });
        }

        if (timeRequest && !hasConflict) {
            await sendBookingNotification(client, {
                receiverID: 'staff-inbox',
                bookingID:  updatedBooking.bookingID,
                title:      'Extra Time Requested',
                message:    `${updatedBooking.clientName || updatedBooking.userID} requested +30 min on their ${svcLabel} booking.`,
                type:       'ALERT',
            });
        }

        if (timeResponse === 'approved') {
            await sendBookingNotification(client, {
                receiverID: updatedBooking.userID,
                bookingID:  updatedBooking.bookingID,
                title:      'Extra Time Approved',
                message:    `Your +30 minute request for ${svcLabel} has been approved.`,
            });
        }

        if (timeResponse === 'rejected') {
            await sendBookingNotification(client, {
                receiverID: updatedBooking.userID,
                bookingID:  updatedBooking.bookingID,
                title:      'Extra Time Request Denied',
                message:    `Your +30 minute request for ${svcLabel} was not approved.`,
            });
        }

        // Return edit success response
        return res.status(200).json({
            success: true,
            message: 'Booking updated successfully',
            data: {
                _id: updatedBooking._id,
                bookingID: updatedBooking.bookingID,
                userID: updatedBooking.userID,
                serviceID: updatedBooking.serviceID,
                status: updatedBooking.status,
                timestamp: updatedBooking.timestamp,
                duration: updatedBooking.duration,
                clientName: updatedBooking.clientName
            }
        });

    } catch (error) {
        console.log(error);
        res.status(500).json({
            success: false,
            message: 'Error updating booking',
            error: error.message
        });
    }
});

// DELETE /delete - Remove a booking from the database
router.delete('/delete', async (req, res) => {
    try {
        const { bookingID } = req.body;

        if (!bookingID) {
            return res.status(400).json({
                success: false,
                message: 'Validation error',
                error: 'bookingID is required'
            });
        }

        const client = await mongodbPromise;
        const database = client.db('services');
        const bookingsCollection = database.collection('bookings');

        const result = await bookingsCollection.deleteOne({ bookingID });

        if (result.deletedCount === 0) {
            return res.status(404).json({
                success: false,
                message: 'Booking not found',
                error: `No booking found with bookingID: ${bookingID}`
            });
        }

        return res.status(200).json({
            success: true,
            message: 'Booking deleted successfully'
        });

    } catch (error) {
        console.log(error);
        res.status(500).json({
            success: false,
            message: 'Error deleting booking',
            error: error.message
        });
    }
});

/* * POST /userbookinghistory :
 *      summary: Get booking history for a specific user
 *
 *      requestBody:
 *          required: true
 *          content:
 *              json:
 *                schema:
 *                  properties:
 *                    userID:
 *                      type: string
 *                  required:
 *                    - userID
 *      responses:
 *        200:
 *          description: - json with array of bookings sorted by timestamp (most recent first)
 *        400:
 *          description: - error message when userID is missing or invalid
 *        500:
 *          description: - json with an error message if there is an issue connecting to MongoDB
 * */
router.post('/userbookinghistory', async (req, res) => {
    try {
        // Extract and validate userID from request body
        const { userID } = req.body;

        if (!userID || typeof userID !== 'string') {
            return res.status(400).send('userID is required and must be a string');
        }

        // Note: Removed YA_xxx pattern validation to allow client names as userID

        // Get MongoDB client and connect to bookings collection
        const client = await mongodbPromise;
        const database = client.db('services');
        const collection = database.collection('bookings');

        // Query for all bookings with matching userID, sorted by timestamp (descending)
        const bookings = await collection
            .find({ userID })
            .sort({ timestamp: -1 })
            .toArray();

        // Return bookings array (empty array if no bookings found)
        return res.status(200).json({ bookings });

    } catch (error) {
        console.log(error);
        res.status(500).send({
            'message': 'Error connecting to MongoDB: ',
            error
        });
    }
});

/**
 * GET /getByBookingID - Get a single booking by bookingID
 * Query param: bookingID (string)
 */
router.get('/getByBookingID', async (req, res) => {
    try {
        const { bookingID } = req.query;

        if (!bookingID) {
            return res.status(400).json({ message: 'bookingID is required' });
        }

        const client = await mongodbPromise;
        const database = client.db('services');
        const collection = database.collection('bookings');

        const booking = await collection.findOne({ bookingID });

        if (!booking) {
            return res.status(404).json({ message: 'Booking not found' });
        }

        return res.status(200).json({ booking });

    } catch (error) {
        console.log(error);
        res.status(500).send({
            'message': 'Error connecting to MongoDB',
            error
        });
    }
});

/**
 * GET /all - Get all bookings
 * Returns all bookings in the database, sorted by timestamp (most recent first)
 * Used by the calendar to display all bookings
 */
router.get('/all', async (req, res) => {
    try {
        const client = await mongodbPromise;
        const database = client.db('services');
        const collection = database.collection('bookings');

        // Get all bookings, sorted by timestamp (descending)
        const bookings = await collection
            .find({ status: { $ne: 'canceled' } })
            .sort({ timestamp: -1 })
            .toArray();

        return res.status(200).json({ bookings });

    } catch (error) {
        console.log(error);
        res.status(500).send({
            'message': 'Error connecting to MongoDB',
            error
        });
    }
});

module.exports = router;