const express = require('express');
const router = express.Router();
const mongodbPromise = require('../utils/mongodb');
const { bookingSchema, bookingCreationSchema } = require('../schemas/booking');

/**
 * Booking Routes
 *
 * ENDPOINTS:
 * - POST /create          - Create a new booking
 * - PUT /edit             - Update an existing booking
 * - DELETE /delete        - Delete a booking
 * - POST /userbookinghistory - Get all bookings for a user
 * - POST /reset-counter   - Reset booking ID counter (testing only)
 *
 * WHAT CLIENT PASSES TO /create:
 * - userID: string        - ID of the authenticated user (e.g., "YA_1")
 * - serviceID: string     - Type of service (e.g., "services", "laundry")
 * - duration: array       - Array with day and time info:
 *     - day: string       - Day of week (e.g., "monday", "tuesday")
 *     - startTime: string - Start time in HH:mm format (e.g., "09:00")
 *     - endTime: string   - End time in HH:mm format (e.g., "10:00")
 * - clientName: string    - Display name for the client (e.g., "John Doe")
 *
 * AUTO-GENERATED BY SERVER:
 * - bookingID: number            - Auto-incrementing unique ID
 * - status: string               - Always starts as 'pending'
 * - timestamp: Date              - Current date/time when created/modified
 * - activity: [{string: string}] - Activity log of the booking
 */

// POST /create - Create a new booking
router.post('/create', async (req, res) => {
    try {

        const { inputError } = bookingCreationSchema.validate(req.body);

        if (inputError) {
            return res.status(400).send(error.details[0].message);
        }
        
        // Get MongoDB client and connect to services database
        const client = await mongodbPromise;
        const database = client.db('services');
        const bookingsCollection = database.collection('bookings');

        const generateBookingID = () => {
            return Array.from({ length: 5 }, () => 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
            .charAt(Math.floor(Math.random() * 36))).join('');
        };

        let bookingID;
        let bookingIDExists = false;

        // Checking if the generated ID exists in Mongo
        while (!bookingIDExists) {
            bookingID = generateBookingID();
            const result = await bookingsCollection.findOne({ bookingID });
            bookingIDExists = !result ? true : false; //kill loop if bookingID doesn't exist

        }

        const timestamp = new Date().toLocaleString('en-US', {
                                    weekday: 'long',
                                    month: 'short',
                                    day: 'numeric',
                                    hour: 'numeric',
                                    minute: '2-digit',
                                    hour12: true
                                });

        // Build the booking data with auto-generated fields
        const bookingData = {
            userID: req.body.userID,
            serviceID: req.body.serviceID,
            bookingID,
            status: 'pending',
            timestamp,
            duration: req.body.duration,
            clientName: req.body.clientName || '',
            activity: [['created', `Created on ${ timestamp }.`],
                        ['pending', `Pending on ${ timestamp }.`]]
        };

        // Validate the complete booking data against Joi schema
        const { error } = bookingSchema.validate(bookingData);

        if (error) {
            return res.status(400).json({
                success: false,
                message: 'Validation error',
                error: error.details[0].message
            });
        }

        // Insert the booking into MongoDB
        const result = await bookingsCollection.insertOne(bookingData);

        return res.status(201).json({
            success: true,
            message: 'Booking created successfully',
            data: {
                _id: result.insertedId,
                bookingID: bookingData.bookingID,
                userID: bookingData.userID,
                serviceID: bookingData.serviceID,
                status: bookingData.status,
                timestamp: bookingData.timestamp,
                duration: bookingData.duration,
                clientName: bookingData.clientName
            }
        });

    } catch (error) {
        console.log(error);

        // Handle duplicate bookingID error
        if (error.code === 11000) {
            return res.status(409).json({
                success: false,
                message: 'Booking already exists',
                error: 'Duplicate bookingID'
            });
        }

        res.status(500).json({
            success: false,
            message: 'Error creating booking',
            error: error.message
        });
    }
});

// PUT /edit - Edit an existing booking's status and/or duration
// Client passes: bookingID and optionally status and/or duration
router.put('/edit', async (req, res) => {
    try {
        // Get MongoDB client and connect to services database
        const client = await mongodbPromise;
        const database = client.db('services');
        const bookingsCollection = database.collection('bookings');

        const { bookingID, status, duration, clientName, serviceID } = req.body;

        // Validate required field
        if (!bookingID) {
            return res.status(400).json({
                success: false,
                message: 'Validation error',
                error: 'Valid bookingID is required'
            });
        }

        // Check that at least one field to update is provided
        if (!status && !duration && !clientName && !serviceID) {
            return res.status(400).json({
                success: false,
                message: 'Validation error',
                error: 'At least one field (status, duration, clientName,'
                     + ' or serviceID) must be provided for update'
            });
        }

        const timestamp = new Date().toLocaleString('en-US', {
            weekday: 'long',
            month: 'short',
            day: 'numeric',
            hour: 'numeric',
            minute: '2-digit',
            hour12: true
        });
        
        // Build the update object dynamically
        const updateFields = {
            activity: []
        };

        // Validate and add status if provided
        if (status !== undefined) {
            const validStatuses = ['pending', 'confirmed', 'canceled'];
            if (!validStatuses.includes(status)) {
                return res.status(400).json({
                    success: false,
                    message: 'Validation error',
                    error: `status must be one of: ${validStatuses.join(', ')}`
                });
            }
            const capitalizedStatus = status.charAt(0).toUpperCase() + status.slice(1);

            updateFields.activity.push([status, `${capitalizedStatus} on ${timestamp}`]);
            updateFields.status = status;
        } else {
            updateFields.activity.push(['modified', `Modified on ${timestamp}.`]);
        }

        // Validate and add duration if provided
        if (duration !== undefined) {
            // Use Joi to validate duration structure
            const Joi = require('joi');
            const durationSchema = Joi.array().items(
                Joi.object({
                    day: Joi.string().valid('sunday', 'monday', 'tuesday', 'wednesday',
                                            'thursday', 'friday', 'saturday').required(),
                    startTime: Joi.string().pattern(/^\d{2}:\d{2}$/).required(),
                    endTime: Joi.string().pattern(/^\d{2}:\d{2}$/).required()
                }).required()
            ).required();

            const { error } = durationSchema.validate(duration);
            if (error) {
                return res.status(400).json({
                    success: false,
                    message: 'Validation error',
                    error: error.details[0].message
                });
            }
            updateFields.duration = duration;
        }

        // Add clientName if provided
        if (clientName !== undefined) {
            updateFields.clientName = clientName;
        }

        // Add serviceID if provided
        if (serviceID !== undefined) {
            updateFields.serviceID = serviceID;
        }

        // Find and update the booking
        const { activity, ...setFields } = updateFields;

        const updatedBooking = await bookingsCollection.findOneAndUpdate(
            { bookingID: bookingID },
            { 
                $set: setFields,
                $push: { activity: { $each: activity } }
            },
            { returnDocument: 'after' } // Return the updated document
        );

        // Check if booking was found
        if (!updatedBooking) {
            return res.status(404).json({
                success: false,
                message: 'Booking not found',
                error: `No booking found with bookingID: ${bookingID}`
            });
        }

        // Return edit success response
        return res.status(200).json({
            success: true,
            message: 'Booking updated successfully',
            data: {
                _id: updatedBooking._id,
                bookingID: updatedBooking.bookingID,
                userID: updatedBooking.userID,
                serviceID: updatedBooking.serviceID,
                status: updatedBooking.status,
                timestamp: updatedBooking.timestamp,
                duration: updatedBooking.duration,
                clientName: updatedBooking.clientName
            }
        });

    } catch (error) {
        console.log(error);
        res.status(500).json({
            success: false,
            message: 'Error updating booking',
            error: error.message
        });
    }
});

/**
 * input that /create
 * userID
 * serviceID
 * duration
 * 
 * input that /edit requires
 * bookingID
 * status
 * AND OR
 * duration
 * 
 * input that /delete requires
 * bookingID
 * 
 * I think from a security point of view, we need someway to authenticate users who try to /edit or /delete.
 * this could be done using JWT's, confirming that only admins are executing these functions
 */

//questions
/**
 * what is an example input?
 * 
 */

/* * POST /userbookinghistory :
 *      summary: Get booking history for a specific user
 *
 *      requestBody:
 *          required: true
 *          content:
 *              json:
 *                schema:
 *                  properties:
 *                    userID:
 *                      type: string
 *                  required:
 *                    - userID
 *      responses:
 *        200:
 *          description: - json with array of bookings sorted by timestamp (most recent first)
 *        400:
 *          description: - error message when userID is missing or invalid
 *        500:
 *          description: - json with an error message if there is an issue connecting to MongoDB
 * */
router.post('/userbookinghistory', async (req, res) => {
    try {
        // Extract and validate userID from request body
        const { userID } = req.body;

        if (!userID || typeof userID !== 'string') {
            return res.status(400).send('userID is required and must be a string');
        }

        // Note: Removed YA_xxx pattern validation to allow client names as userID

        // Get MongoDB client and connect to bookings collection
        const client = await mongodbPromise;
        const database = client.db('services');
        const collection = database.collection('bookings');

        // Query for all bookings with matching userID, sorted by timestamp (descending)
        const bookings = await collection
            .find({ userID })
            .sort({ timestamp: -1 })
            .toArray();

        // Return bookings array (empty array if no bookings found)
        return res.status(200).json({ bookings });

    } catch (error) {
        console.log(error);
        res.status(500).send({
            'message': 'Error connecting to MongoDB: ',
            error
        });
    }
});

/**
 * GET /all - Get all bookings
 * Returns all bookings in the database, sorted by timestamp (most recent first)
 * Used by the calendar to display all bookings
 */
router.get('/all', async (req, res) => {
    try {
        const client = await mongodbPromise;
        const database = client.db('services');
        const collection = database.collection('bookings');

        // Get all bookings, sorted by timestamp (descending)
        const bookings = await collection
            .find({})
            .sort({ timestamp: -1 })
            .toArray();

        return res.status(200).json({ bookings });

    } catch (error) {
        console.log(error);
        res.status(500).send({
            'message': 'Error connecting to MongoDB',
            error
        });
    }
});

module.exports = router;